# Generated by Django 3.2.7 on 2023-10-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=255)),
                ('organizer_name', models.CharField(max_length=255)),
                ('battle_type', models.CharField(max_length=255)),
                ('number_of_team', models.CharField(max_length=255)),
                ('maximum_player_per_team', models.CharField(max_length=255)),
                ('additional_information', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MyTableName',
            },
        ),
    ]
