# Generated by Django 3.2.7 on 2023-10-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createtournament',
            table='CreateTournament',
        ),
    ]
