# Generated by Django 3.2.7 on 2023-10-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_createtournament_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('createtournament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.createtournament')),
            ],
            options={
                'db_table': 'CreateTeam',
            },
        ),
    ]
