# Generated by Django 3.2.7 on 2023-10-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_enterresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('points', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PlacePoints',
            },
        ),
    ]
