# Generated by Django 3.2.7 on 2023-10-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_placepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterresult',
            name='place_points',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterresult',
            name='total',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
