# Generated by Django 3.2.7 on 2023-11-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20231031_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterresult',
            name='team_id',
        ),
        migrations.AddField(
            model_name='enterresult',
            name='tourament_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.createtournament'),
        ),
    ]
