# Generated by Django 3.2.7 on 2023-11-01 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20231101_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnterResult',
            new_name='TempEnterResult',
        ),
        migrations.AlterModelTable(
            name='tempenterresult',
            table='TempEnterResult',
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('place_points', models.CharField(max_length=255)),
                ('kill', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('match', models.CharField(max_length=255)),
                ('tourament_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.createtournament')),
            ],
            options={
                'db_table': 'Result',
            },
        ),
    ]
