# Generated by Django 3.2.7 on 2023-11-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20231101_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempenterresult',
            name='match',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
