# Generated by Django 3.2.7 on 2023-11-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20231103_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePointsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PlacePointsImage',
            },
        ),
    ]
