# Generated by Django 3.2.7 on 2023-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_placepointsimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='placepointsimage',
            name='counter_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
