# Generated by Django 3.2.7 on 2023-11-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_placepointsimage_counter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placepointsimage',
            name='counter_number',
        ),
    ]
